needs-triage:
- changed-files:
  - any-glob-to-any-file: 'proposals/**/*'

language-spec:
- changed-files:
  - any-glob-to-any-file: 'spec/**/*'

# Apply the normative label to any change to latex that extends beyond an annex
# or the macros file.
normative:
- changed-files:
  - any-glob-to-any-file: 'spec/**/*.tex'

documentation:
- any:
  - changed-files:
    - all-globs-to-any-file:
      - 'docs/**/*.md'
      - '!docs/Meetings/*.md' # Ignore meeting files
  - changed-files:
    - any-glob-to-any-file:
      - 'README.md'
      - 'CONTRIBUTING.md'

website:
- changed-files:
    - any-glob-to-any-file:
      - 'assets/**/*'
      - 'website/**/*'

agenda:
- changed-files:
  - any-glob-to-any-file: 'docs/Meetings/*-agenda.md'

minutes:
- changed-files:
  - any-glob-to-any-file: 'docs/Meetings/*-minutes.md'

infrastructure:
- changed-files:
  - any-glob-to-any-file:
    - '.github/**/*'
    - 'scripts/**/*'
    - 'Dockerfile'
    - 'docker-compose.yml'
    - 'CODEOWNERS'
